### ISSUE TITLE
Outdated semgrep version

### ISSUE THREAD

**Issue by H4dr1en** [DataDog/guarddog#249]
On macos Ventura 13.4, using miniconda env with python3.10, 

Using:

```
pip install guarddog
```
will install `semgrep==0.112.1`as defined in the `requirements.txt`

Then running it on a local package will fail:
```
 $ guarddog pypi scan .                            
Found 0 potentially malicious indicators scanning .

Some rules failed to run while scanning .:

* rules-all: failed to run rule: 
An error occurred when running Semgrep.

command: semgrep --config /opt/miniconda3/lib/python3.10/site-packages/guarddog/analyzer/sourcecode --exclude='helm' --exclude='.idea' --exclude='venv' --exclude='test' --exclude='tests' --exclude='.env' --exclude='dist' --exclude='build' --exclude='semgrep' --exclude='migrations' --exclude='.github' --exclude='.semgrep_logs' --no-git-ignore --json --quiet .
status code: 2
output: {"errors": [{"code": 2, "level": "error", "message": "Error while running rules: 0 bytes read on a total of 2 expected bytes", "type": "SemgrepError"}], "paths": {"_comment": "<add --verbose for a list of skipped paths>", "scanned": []}, "results": [], "version": "0.112.1"}
```

Now updating to latest semgrep using `pip install -U semgrep` and running the same command above:
```
 $ guarddog pypi scan .
Found 0 potentially malicious indicators scanning .
```

What is the reason for using semgrep 0.112.1 and not latest?

**Comment by christophetd** [comment]
Hello,

The reason is that we did not manage to upgrade to Semgrep past 0.112.1 without breaking the current detection rules due to a Semgrep internal error we have been unable to troubleshoot (https://github.com/returntocorp/semgrep/issues/6631)

<img width="1021" alt="image" src="https://github.com/DataDog/guarddog/assets/136675/f48d0a60-0b8b-41b9-a32e-f1b2506e2ec9">

v.s. (starting from 0.113.0)

<img width="2195" alt="image" src="https://github.com/DataDog/guarddog/assets/136675/afad8be0-7eaf-488e-8e97-e521bbd20708">

We welcome a contribution if someone wants to give it a try!

In the meantime, although outdated, Semgrep 0.112.1 is supposed to properly work as-is - if not, it's an unexpected bug. Can you open a new issue to track it, ideally sharing the package you're scanning as well? Thank you

**Comment by H4dr1en** [comment]
Got it - do you have an issue to keep track of this already? Otherwise let's use this one

**Comment by christophetd** [comment]
We don't - thanks

**Comment by AngellusMortis** [comment]
Is there any way you can work around the issue? There has been zero traction on the other issue and 0.112 of semgrep also [requires a outdated version of packaging](https://github.com/returntocorp/semgrep/issues/7033) as well.

**Comment by christophetd** [comment]
The best way around would be to get someone to troubleshoot the failing rule when we attempt to upgrade Semgrep (as shown in https://user-images.githubusercontent.com/136675/247486778-afad8be0-7eaf-488e-8e97-e521bbd20708.png). It has not been prioritized yet from our side, but we're happy to take a community contribution
